Repository PedestrianDynamics/jupedsim, pull requests merged in 2019-10, with the labels that each got.

#507 Adds clang-format-hooks as third party lib
  .travis.yml
  .travis_install.bash
  third-party/.clang-format
  third-party/clang-format-hooks/COPYING
  third-party/clang-format-hooks/README.md
  third-party/clang-format-hooks/apply-format
  third-party/clang-format-hooks/git-pre-commit-format
  third-party/clang-format-hooks/run-checks
Labels: Priority: Low, Status: Completed, Type: Enhancement, Type: Refactoring

#499 Adds SPDLog based logging
  IO/GeoFileParser.cpp
  Simulation.cpp
  general/Format.h
  main.cpp
Labels: Priority: Medium, Status: In Progress, Type: Refactoring

#483 First step to more general output
  CHANGELOG.md
  IO/IODispatcher.cpp
  IO/IODispatcher.h
  IO/IniFileParser.cpp
  Simulation.cpp
  general/Configuration.h
  general/Macros.h
  pedestrian/Pedestrian.cpp
  routing/ff_router/FloorfieldViaFM.cpp
  routing/ff_router/UnivFFviaFM.cpp
  routing/ff_router_trips/FloorfieldViaFMTrips.cpp
  routing/ff_router_trips/UnivFFviaFMTrips.cpp
Labels: Priority: Low
