Repository PedestrianDynamics/jupedsim, pull requests merged in 2020-06, with the labels that each got.

#786 754 output precision
  docs/pages/jpscore/jpscore_inifile.md
  libcore/src/IO/IniFileParser.cpp
  libcore/src/IO/Trajectories.cpp
  libcore/src/IO/Trajectories.h
  libcore/src/Simulation.cpp
  libcore/src/general/Configuration.h
Labels: Type: Enhancement

#789 Events
  libcore/CMakeLists.txt
  libcore/src/IO/EventFileParser.cpp
  libcore/src/IO/EventFileParser.h
  libcore/src/IO/TrainFileParser.cpp
  libcore/src/Simulation.cpp
  libcore/src/events/DoorEvent.cpp
  libcore/src/events/DoorEvent.h
  libcore/src/events/Event.cpp
  libcore/src/events/Event.h
  libcore/src/events/EventHelper.cpp
  libcore/src/events/EventHelper.h
  libcore/src/events/EventManager.cpp
  libcore/src/events/EventManager.h
  libcore/src/events/TrainEvent.cpp
  libcore/src/events/TrainEvent.h
  libshared/Logger.h
Labels: Type: Refactoring

#804 Update GCC to version 9 and Ubuntu to 20.04
  CMakeLists.txt
  container/build/Dockerfile
Labels: Type: Maintenance

#806 Link jpsreport with OpenMP if available
  jpsreport/CMakeLists.txt
Labels: Type: Bug
