Repository PedestrianDynamics/jupedsim, pull requests merged in 2020-02, with the labels that each got.

#670 Issue 669 method A
  CMakeLists.txt
  docs/pages/jpsreport/jpsreport_inifile.md
  jpsreport/Analysis.cpp
  jpsreport/methods/Method_A.cpp
  jpsreport/methods/Method_A.h
  jpsreport/methods/PedData.cpp
  jpsreport/methods/PedData.h
  systemtest/jpsreport_tests/method_A/test2/02_method_A.py
  systemtest/jpsreport_tests/method_A/test2/geometry.xml
  systemtest/jpsreport_tests/method_A/test2/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test2/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test3/03_method_A.py
  systemtest/jpsreport_tests/method_A/test3/geometry.xml
  systemtest/jpsreport_tests/method_A/test3/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test3/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test4/04_method_A.py
  systemtest/jpsreport_tests/method_A/test4/geometry.xml
  systemtest/jpsreport_tests/method_A/test4/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test4/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test5/05_method_A.py
  systemtest/jpsreport_tests/method_A/test5/geometry.xml
  systemtest/jpsreport_tests/method_A/test5/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test5/jpsreport_ini.xml
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#668 Refactoring testing of jpsreport
  CMakeLists.txt
  cmake_modules/helper_functions.cmake
  container/build/Dockerfile
  docs/pages/jupedsim/jupedsim_install_on_windows.md
  systemtest/CMakeLists.txt
  systemtest/JPSRunTest.py
  systemtest/jpsreport_tests/CMakeLists.txt
  systemtest/jpsreport_tests/method_A/test01/01_method_A.py
  systemtest/jpsreport_tests/method_A/test01/geometry.xml
  systemtest/jpsreport_tests/method_A/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test01/reference_data_Method_A_Flow_NT.dat
  systemtest/jpsreport_tests/method_A/test01/traj.txt
  systemtest/jpsreport_tests/method_A/test02/02_method_A.py
  systemtest/jpsreport_tests/method_A/test02/geometry.xml
  systemtest/jpsreport_tests/method_A/test02/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test02/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test02/traj.txt
  systemtest/jpsreport_tests/method_A/test03/03_method_A.py
  systemtest/jpsreport_tests/method_A/test03/geometry.xml
  systemtest/jpsreport_tests/method_A/test03/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test03/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test03/traj.txt
  systemtest/jpsreport_tests/method_A/test04/04_method_A.py
  systemtest/jpsreport_tests/method_A/test04/geometry.xml
  systemtest/jpsreport_tests/method_A/test04/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test04/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test04/traj.txt
  systemtest/jpsreport_tests/method_A/test05/05_method_A.py
  systemtest/jpsreport_tests/method_A/test05/geometry.xml
  systemtest/jpsreport_tests/method_A/test05/jpscore_ini.xml
  systemtest/jpsreport_tests/method_A/test05/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_A/test05/traj.txt
  systemtest/jpsreport_tests/method_B/test01/01_method_B.py
  systemtest/jpsreport_tests/method_B/test01/geometry.xml
  systemtest/jpsreport_tests/method_B/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_B/test01/reference_data_Method_B.dat
  systemtest/jpsreport_tests/method_B/test01/traj.txt
  systemtest/jpsreport_tests/method_C/test01/01_method_C.py
  systemtest/jpsreport_tests/method_C/test01/geometry.xml
  systemtest/jpsreport_tests/method_C/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_C/test01/reference_data_Method_C.dat
  systemtest/jpsreport_tests/method_C/test01/traj.txt
  systemtest/jpsreport_tests/method_D/test01/01_method_D.py
  systemtest/jpsreport_tests/method_D/test01/geometry.xml
  systemtest/jpsreport_tests/method_D/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_D/test01/reference_data_Method_D_IFD.dat
  systemtest/jpsreport_tests/method_D/test01/traj.txt
  systemtest/jpsreport_tests/method_I/test01/01_method_I.py
  systemtest/jpsreport_tests/method_I/test01/geometry.xml
  systemtest/jpsreport_tests/method_I/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_I/test01/reference_data_Method_I_IFD.dat
  systemtest/jpsreport_tests/method_I/test01/traj.txt
  systemtest/jpsreport_tests/method_J/test01/01_method_J.py
  systemtest/jpsreport_tests/method_J/test01/geometry.xml
  systemtest/jpsreport_tests/method_J/test01/jpsreport_ini.xml
  systemtest/jpsreport_tests/method_J/test01/reference_data_Method_J.dat
  systemtest/jpsreport_tests/method_J/test01/traj.txt
  systemtest/utils.py
Labels: JPSreport, Status: Review Needed, Type: Refactoring

#704 Remove juelich tests 10 15
  docs/pages/jpscore/jpscore_tests_juelich.md
  systemtest/juelich_tests/CMakeLists.txt
  systemtest/juelich_tests/test_10/geometry.xml
  systemtest/juelich_tests/test_10/master_ini.xml
  systemtest/juelich_tests/test_10/runtest_juelich_10.py
  systemtest/juelich_tests/test_14/master_ini.xml
  systemtest/juelich_tests/test_15/geometry.xml
  systemtest/juelich_tests/test_15/master_ini.xml
  systemtest/juelich_tests/test_15/runtest_juelich_15.py
Labels: Type: Maintenance

#710 Changes Keyserver due to timeout.
  container/build/Dockerfile
Labels: Priority: High

#702 Update documentation
  docs/pages/jpsreport/jpsreport_introdcution.md
Labels: Type: Documentation

#703 refactor test 11
  systemtest/juelich_tests/test_11/a_runtest.py
  systemtest/juelich_tests/test_11/b_runtest.py
  systemtest/juelich_tests/test_11/master_ini_a.xml
  systemtest/juelich_tests/test_11/runtest_juelich_11.py
  systemtest/juelich_tests/test_3/master_ini.xml
Labels: Type: Maintenance

#671 remove subprocess call in test driver
  systemtest/JPSRunTest.py
  systemtest/makeini.py
Labels: Priority: Low, Type: Maintenance

#705 Add some information to installation of deps
  docs/pages/jupedsim/jupedsim_install_on_linux.md
Labels: Type: Documentation, Type: Maintenance
